[package]
name = "isup"
version = "0.1.0"
edition = "2021"
description = "A CLI tool to check if a website or service is up"
authors = ["Your Name"]

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
colored = "2.0"
